name: C/C++ CI

on:
  pull_request:
    branches: [ "master,main" ]
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y gcc make

    - name: Build
      run: make all

    - name: Run tests
      run: make run-all
